    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    genre TEXT,
    release_year INT
);

INSERT INTO videogames (title, genre, release_year) VALUES
('The Legend of Zelda', 'Adventure', 1986),
('Dark Souls', 'RPG', 2011),
('Minecraft', 'Sandbox', 2011);
